# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  main-test:
    name: Main test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps: 
      - uses: actions/checkout@v2
      - name: Use Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Running tests
        run: yarn test
     
  ember-try-required: 
    name: Running ember-try on ember version, ${{ matrix.scenario }}
    
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix: 
        scenario: [lts-3.8, lts-3.12, lts-3.15]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps: 
      - uses: actions/checkout@v2
      - name: Use Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Running test
        run: yarn ember try:one ${{ matrix.scenario }}

  ember-try-optional:
    name: Running ember-try on ember version, ${{ matrix.scenario }}
    
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix: 
        scenario: [ember-beta, ember-release, ember-canary]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps: 
      - uses: actions/checkout@v2
      - name: Use Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Running test
        run: yarn ember try:one ${{ matrix.scenario }}
